# Generated by Django 5.0.1 on 2024-01-30 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoDuro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.IntegerField(max_length=100)),
                ('capacidad', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MemoriaRam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=15)),
                ('capacidad', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=15)),
                ('capacidad', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.IntegerField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('disco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.discoduro')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.memoriaram')),
                ('procesador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.procesador')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('documento', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=250)),
                ('id_pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.computador')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.computador')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.tecnico')),
            ],
        ),
    ]
