# Generated by Django 5.0.1 on 2024-01-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='id_pc',
        ),
    ]
