# Generated by Django 5.0.1 on 2024-01-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_tecnico_id_pc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoduro',
            name='marca',
            field=models.CharField(max_length=100),
        ),
    ]
